spring:
  datasource:
    url: jdbc:mariadb://${testDbIp:127.0.0.1}:3306/app868__test?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: lldjlocal
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
custom:
  genFileDirPath: c:/temp/app10
logging:
  level:
    com.ll.exam.app676.app: debug