spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            clientId: NEED_TO_INPUT

custom:
  jwt:
    secretKey: password_secret_password_secret_password_secret_password_secret_password_secret